# Generated by Django 5.1.1 on 2024-12-08 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0, verbose_name='Số dư')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Tiêu đề chương')),
                ('number', models.IntegerField(verbose_name='Số thứ tự')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên lớp')),
                ('start_time', models.DateField(auto_now_add=True, null=True, verbose_name='Thời gian mở lớp')),
                ('end_time', models.DateField(null=True, verbose_name='Thời gian đóng lớp')),
                ('status', models.CharField(choices=[('active', 'active'), ('upcoming', 'upcoming'), ('completed', 'completed')], default='upcoming', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Tên khóa học')),
                ('teacher', models.CharField(max_length=200, null=True, verbose_name='Tên giảng viên')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên kỳ học')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('total_of_months', models.IntegerField(verbose_name='Tổng số tháng cho học kỳ')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Tên đăng nhập')),
                ('password', models.CharField(max_length=100, verbose_name='Mật khẩu')),
            ],
        ),
        migrations.CreateModel(
            name='ContentOfChapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Tiêu đề nội dung')),
                ('content', models.TextField(verbose_name='Nội dung của chương')),
                ('number', models.IntegerField(verbose_name='Số thứ tự đề mục')),
                ('link', models.URLField(max_length=250, verbose_name='Liên kết')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.chapter', verbose_name='Thông tin chương')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.course', verbose_name='Thông tin khóa học của chương'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên môn học')),
                ('class_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.class', verbose_name='Lớp chứa môn học')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_execution', models.DateField(auto_now_add=True, verbose_name='Ngày tiến hành')),
                ('start', models.TimeField(verbose_name='Thời gian bắt đầu')),
                ('end', models.TimeField(verbose_name='Thời gian kết thúc')),
                ('type', models.CharField(choices=[('learn', 'learn'), ('review', 'review'), ('practice', 'practice')], default='prac', max_length=10)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Tiêu đề tài liệu')),
                ('link', models.URLField(max_length=250, null=True, verbose_name='Liên kết')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.subject', verbose_name='Thông tin môn học')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.subject', verbose_name='Thông tin môn học của khóa'),
        ),
        migrations.AddField(
            model_name='class',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.term', verbose_name='Thông tin kỳ học'),
        ),
        migrations.CreateModel(
            name='Transactiona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200, verbose_name='Nội dung giao dịch')),
                ('value', models.FloatField(verbose_name='Giá trị giao dịch')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.balance', verbose_name='Thông tin tài khoản người dùng')),
            ],
        ),
        migrations.AddField(
            model_name='term',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.user', verbose_name='Thông tin người dùng'),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='main_site.user', verbose_name='Tài khoản người dùng'),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, null=True, verbose_name='Số điện thoại')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Địa chỉ')),
                ('dob', models.DateField(null=True, verbose_name='Ngày sinh')),
                ('school', models.CharField(max_length=50, null=True, verbose_name='Thông tin trường học')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='main_site.user', verbose_name='Tài khoản người dùng')),
            ],
        ),
    ]
