# Generated by Django 5.1.1 on 2024-12-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactiona',
            new_name='Transaction',
        ),
    ]
