# Generated by Django 5.1.1 on 2024-12-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_rename_transactiona_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='link',
            field=models.URLField(default='http://example.com', max_length=250, verbose_name='Nguồn khóa học'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='term',
            name='total_of_months',
            field=models.IntegerField(verbose_name='Tổng số tháng dự kiến cho học kỳ'),
        ),
    ]
