# Generated by Django 5.1.1 on 2024-12-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_chapter_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date_of_execution',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start',
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01', verbose_name='Thời gian bắt đầu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[('learn', 'learn'), ('review', 'review'), ('practice', 'practice')], default='practice', max_length=10),
        ),
    ]
