# Generated by Django 5.1.1 on 2024-12-23 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_remove_session_date_of_execution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='subject',
        ),
        migrations.AddField(
            model_name='session',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.course'),
        ),
    ]
