# Generated by Django 5.1.1 on 2024-12-23 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_remove_session_subject_session_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên ca làm việc')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bắt mở ca')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='Shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.shift'),
        ),
    ]
