# Generated by Django 5.1.1 on 2024-12-23 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_shift_session_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='chapter',
            field=models.ManyToManyField(to='main_site.chapter', verbose_name='Các chương học trong buổi'),
        ),
        migrations.AddField(
            model_name='session',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.class'),
        ),
        migrations.AddField(
            model_name='session',
            name='note',
            field=models.TextField(default='Non', verbose_name='Ghi chú'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.subject'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian mở ca'),
        ),
    ]
