# Generated by Django 5.1.1 on 2024-12-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_session_chapter_session_class_obj_session_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='Shift',
            new_name='shift',
        ),
    ]
