# Generated by Django 5.1.1 on 2024-12-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_rename_shift_session_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='chapter',
            field=models.ManyToManyField(blank=True, null=True, to='main_site.chapter', verbose_name='Các chương học trong buổi'),
        ),
    ]
