# Generated by Django 5.1.1 on 2024-12-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0014_rename_balance_balance_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
