# Generated by Django 5.1.1 on 2024-12-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0015_alter_session_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End time of Shift'),
        ),
    ]
