# Generated by Django 5.1.1 on 2024-12-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0016_alter_shift_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
