# Generated by Django 5.1.1 on 2024-12-30 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0017_shift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='maxOfDay',
            field=models.IntegerField(default=50, verbose_name='Số lượng ngày học tối đa trong kỳ'),
        ),
        migrations.AddField(
            model_name='class',
            name='maxOfSessionsInDay',
            field=models.IntegerField(default=2, verbose_name='Số lượng buổi học tối đa trong ngày'),
        ),
        migrations.CreateModel(
            name='DayPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(verbose_name='Số thứ tự ngày học')),
                ('classObj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_site.class', verbose_name='Thông tin lớp học')),
            ],
        ),
        migrations.CreateModel(
            name='SessionPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(verbose_name='Số thứ tự của buổi học')),
                ('status', models.BooleanField(verbose_name='Trạng thái buổi học')),
                ('content', models.TextField(verbose_name='Content of Session')),
                ('type', models.CharField(choices=[('learn', 'learn'), ('review', 'review'), ('practice', 'practice')], default='learn', max_length=10)),
                ('iCode', models.CharField(max_length=10, verbose_name='Mã số session')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.daypathway', verbose_name='Day of this session')),
            ],
        ),
    ]
