# Generated by Django 5.1.1 on 2024-12-31 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0020_remove_transaction_balance_transaction_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên loại giao dịch')),
                ('maxValue', models.ImageField(upload_to='', verbose_name='Hạn mức tối đa mỗi tháng')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.typeoftransaction'),
        ),
    ]
