# Generated by Django 5.1.1 on 2024-12-31 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0021_typeoftransaction_alter_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='typeOfTransaction',
        ),
    ]
