# Generated by Django 5.1.1 on 2024-12-31 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0022_rename_type_transaction_typeoftransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='typeOfTransaction',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
