# Generated by Django 5.1.1 on 2024-12-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0023_alter_transaction_typeoftransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='typeOfTransaction',
        ),
    ]
