# Generated by Django 5.1.1 on 2025-01-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0030_deadline_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
